/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_example_gpuimage_GPUImageNativeLibrary */

#ifndef _Included_com_zhangjunling_example_gpuimage_GPUImageNativeLibrary
#define _Included_com_zhangjunling_example_gpuimage_GPUImageNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_example_gpuimage_GPUImageNativeLibrary
 * Method:    YUVtoRBGA
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_gpuimage_GPUImageNativeLibrary_YUVtoRBGA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     com_zhangjunling_example_gpuimage_GPUImageNativeLibrary
 * Method:    YUVtoARBG
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_gpuimage_GPUImageNativeLibrary_YUVtoARBG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
